### ISSUE TITLE
No item with given ID found / no permission to access

### ISSUE THREAD

**Issue by Jswallow7** [Sheetgo/invoice-generator#3]
I followed the tutorial to set up the automation and it looks like the script is getting stuck with the URL's.   I've made sure to set permissions to anyone can edit with the link in sharing settings for the Doc, Spreadsheet & Folder. Any clarification on what URL we should be pasting in the script?

when I run the generator I get an error stating " No item with the given ID could be found, or you do not have permission to access it"

**Comment by rafaelalemar** [comment]
can you share the spreadsheet and the script with rafael@sheetgo.com? I can check your script to see what are you missing, and then to be able to improve the documentation.
